POST http://localhost:8000/stadium
Content-Type: application/json

{
    "name" : "Stadium 1",
    "capacity" : 100,
    "viprows" : 10,
    "seatsperrow" : 10
}


### 
GET http://localhost:8000/stadium


### 
GET http://localhost:8000/teams