
### register user
POST http://localhost:8000/register
Content-Type: application/json

{
    "username": "walid", 
    "password": "walidwalid",
    "email": "walid@gmail.com",
    "firstName": "walid",
    "lastName": "walid",
    "email": "walid@gmail.com",
    "gender": "male",
    "city": "cairo",
    "address": "cairo",
    "birthDate": "2002-02-02T00:00:00.000Z",
    "role": "customer"
}


### login user
POST http://localhost:8000/login
Content-Type: application/json

{
    "email": "walid@gmail.com", 
    "password": "walidwalid"
}
##### get all users    
GET http://localhost:8000/users


