
### register user
POST http://localhost:8000/register
Content-Type: application/json

{
    "username": "walid", 
    "password": "walidwalid",
    "email": "walid@gmail.com",
    "firstName": "walid",
    "lastName": "walid",
    "email": "walid@gmail.com",
    "gender": "male",
    "city": "cairo",
    "address": "cairo",
    "birthDate": "2002-02-02T00:00:00.000Z",
    "role": "master"
}

### register user
POST http://localhost:8000/register
Content-Type: application/json

{
    "username": "mahermaher", 
    "password": "alyalyaly",
    "email": "maher@gmail.com",
    "firstName": "aly",
    "lastName": "aly",
    "gender": "male",
    "city": "cairo",
    "address": "cairo",
    "birthDate": "2002-02-02T00:00:00.000Z",
    "role": "customer"
}




### login user
POST http://localhost:8000/login
Content-Type: application/json

{
    "email": "walid@gmail.com", 
    "password": "walidwalid"
}


##### get all users    
GET http://localhost:8000/users

###### 
PUT http://localhost:8000/user/update
Content-Type: application/json

{
    "username": "walid", 
    "password": "walidwalid",
    "email": "walid@gmail.com",
    "firstName": "Aly",
    "lastName": "walid",
    "email": "walid@gmail.com",
    "gender": "male",
    "city": "cairo",
    "address": "cairo",
    "birthDate": "2002-02-02T00:00:00.000Z",
    "role": "customer"
}




### approve user 

PUT http://localhost:8000/user/approve
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6IndhbGlkQGdtYWlsLmNvbSIsImV4cCI6MTczMzc4Nzk1MSwicm9sZSI6Im1hc3RlciIsInVzZXJuYW1lIjoid2FsaWQifQ.B7vAlVv8mxI7ysFpra_0ASyopIO81onjjCFNvI_ob7Q

{
    "username": "mahermaher",
    "approved": true
}